# Generated by Django 2.2.1 on 2019-05-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190517_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=64),
        ),
    ]
